### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by joshuacerdenia** [audiolabs/trackswitch.js#8]
I realize this hasn't been updated in 3 years, but just in case: I keep getting a CORS error from trying to load audio files from a domain other than Github. How to fix this?

**Comment by faroit** [comment]
Hi @joshuacerdenia sorry for not getting back to you. I think this this problem is/was out of scope of trackswitch and there is probably nothing we could do about it as this is concerned with browser security. 

Feel free to provide PR to update the documentation for this to make future users aware of this.

**Comment by joshuacerdenia** [comment]
Hi @faroit no problem, I figured that out, that's why I closed the issue. Thanks anyway.
